const { SCHEMA_VERSION } = require('../../shared/rewards');
const DEFAULT_REWARD_CONFIG = {
  global: { pointsPerRand: 10, customerPointExpiryMonths: 6, minimumCustomerRedemptionPoints: 100, redemptionIncrementPoints: 10, maximumServiceCreditPercentagePerBooking: 20, featureFlags: { rewardsEnabled: true, referralsEnabled: true, ratingsEnabled: true, expiryEnabled: true, redemptionEnabled: false }, schemaVersion: SCHEMA_VERSION },
  customer: { rewards: { profileCompleted: 20, paymentMethodVerified: 50, firstCompletedPaidBooking: 100, completedPaidBooking: 50, ratingSubmitted: 20, postServicePhoto: 20, referralStageOne: 100, referralStageTwo: 150, dailyQualifyingActivity: 1, sevenDayStreakBonus: 10, thirtyDayStreakBonus: 30, favouriteAction: 1, shareAction: 1 }, ratingReceivedEffects: { 5: 50, 4: 20, 3: -10, 2: -30, 1: -50 }, lowValueCaps: { dailyQualifyingActivity: 1, favouriteActionPerDay: 5, shareActionPerDay: 5 }, schemaVersion: SCHEMA_VERSION },
  helper: { rewards: { completedPaidJob: 50, fiveStarRating: 50, fourStarRating: 20, belowFourStarEffect: 0, lowCancellationRate: 0, highCompletionRate: 0, fastResponse: 0, referralReward: 0, beforeAfterProof: 0, verificationMaintenance: 0 }, annualPointTiers: [], ratingReceivedEffects: { 5: 50, 4: 20, 3: 0, 2: 0, 1: 0 }, schemaVersion: SCHEMA_VERSION },
  membership: { customer: { neighbour: { minCompletedPaidBookings: 0, minAverageRating: 0, minRatingCount: 0 }, partner: { minCompletedPaidBookings: 10, minAverageRating: 4.0, minRatingCount: 3 }, friend: { minCompletedPaidBookings: 50, minAverageRating: 4.3, minRatingCount: 10, requireNoSevereConductRestriction: true }, family: { minCompletedPaidBookings: 200, minAverageRating: 4.6, minRatingCount: 25, requireNoSevereConductRestriction: true, maxCancellationRate: 0.2 } }, helper: { neighbour: { minCompletedPaidJobs: 0, minAverageRating: 0, minRatingCount: 0 }, partner: { minCompletedPaidJobs: 25, minAverageRating: 4.3, minRatingCount: 5, minCompletionRate: 0.8, maxCancellationRate: 0.2, requireVerified: true }, friend: { minCompletedPaidJobs: 100, minAverageRating: 4.6, minRatingCount: 20, minCompletionRate: 0.9, maxCancellationRate: 0.1, requireVerified: true }, family: { minCompletedPaidJobs: 300, minAverageRating: 4.8, minRatingCount: 50, minCompletionRate: 0.95, maxCancellationRate: 0.05, requireVerified: true } }, schemaVersion: SCHEMA_VERSION },
  mastery: { beginner: { minCompletedPaidJobs: 0, minAverageRating: 0, minRatingCount: 0 }, specialist: { minCompletedPaidJobs: 50, minAverageRating: 4.6, minRatingCount: 10 }, master: { minCompletedPaidJobs: 200, minAverageRating: 4.8, minRatingCount: 40 }, legend: { minCompletedPaidJobs: 500, minAverageRating: 4.9, minRatingCount: 100 }, schemaVersion: SCHEMA_VERSION }
};
async function getRewardConfig(db, section) { const snap = await db.collection('rewardConfig').doc(section).get(); return { ...DEFAULT_REWARD_CONFIG[section], ...(snap.exists ? snap.data() : {}) }; }
async function seedDefaultRewardConfig(db, admin) { const batch = db.batch(); for (const [id, data] of Object.entries(DEFAULT_REWARD_CONFIG)) batch.set(db.collection('rewardConfig').doc(id), { ...data, updatedAt: admin.firestore.FieldValue.serverTimestamp() }, { merge: true }); await batch.commit(); }
module.exports = { DEFAULT_REWARD_CONFIG, getRewardConfig, seedDefaultRewardConfig };
