const { logger } = require('firebase-functions');
const { ACCOUNT_TYPES, RATING_DIRECTIONS, REWARD_REASON_CODES, REWARD_TRANSACTION_DIRECTIONS, SCHEMA_VERSION } = require('../../shared/rewards');
const { getRewardConfig } = require('./config');
const { applyRewardTransaction } = require('./rewardService');
function clampScore(score){ const n=Number(score); if(!Number.isInteger(n)||n<1||n>5) throw new Error('score must be an integer from 1 to 5'); return n; }
function cleanComment(c=''){ return String(c||'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,1000); }
function getParticipants(req){ return {customerId:req.customerId||req.studentId, helperId:req.helperAssignment?.helperId||req.helperId||req.tutorId}; }
function serviceIdsFor(req){ return [...new Set([...(Array.isArray(req.serviceIds)?req.serviceIds:[]), ...(Array.isArray(req.includedServiceIds)?req.includedServiceIds:[]), req.selectedPackageId].filter(Boolean).map(String))]; }
function distInc(field, oldScore, newScore, admin){ const out={}; if(oldScore) out[`${field}.${oldScore}`]=admin.firestore.FieldValue.increment(-1); if(newScore) out[`${field}.${newScore}`]=admin.firestore.FieldValue.increment(1); return out; }
async function submitServiceRequestRating({db,admin,requestId,raterUserId,score,comment}){ const requestRef=db.collection('serviceRequests').doc(requestId); const scoreNum=clampScore(score); const requestSnap=await requestRef.get(); if(!requestSnap.exists) throw new Error('service request not found'); const req=requestSnap.data()||{}; const {customerId,helperId}=getParticipants(req); let direction,ratedUserId,raterRole,ratedRole,embedKey;
 if(raterUserId===customerId){ direction=RATING_DIRECTIONS.CUSTOMER_TO_HELPER; ratedUserId=helperId; raterRole='customer'; ratedRole='helper'; embedKey='customer'; }
 else if(raterUserId===helperId){ direction=RATING_DIRECTIONS.HELPER_TO_CUSTOMER; ratedUserId=customerId; raterRole='helper'; ratedRole='customer'; embedKey='helper'; }
 else throw new Error('Only request participants can submit ratings.'); if(!ratedUserId) throw new Error('No valid rating target was found for this request.');
 const status=String(req.status||'').toLowerCase(); if(!['completed','closed'].includes(status)) throw new Error('This request is not eligible for rating yet.');
 const ratingId=`${requestId}_${direction}`; const ratingRef=db.collection('ratings').doc(ratingId); const services=serviceIdsFor(req); const primary=services[0]||req.categoryId||''; const now=admin.firestore.FieldValue.serverTimestamp(); let previous=null;
 await db.runTransaction(async tx=>{ const old=await tx.get(ratingRef); previous=old.exists?old.data():null; const oldScore=previous?.score||null; const record={ratingId,requestId,direction,raterUserId,raterRole,ratedUserId,ratedRole,categoryId:req.categoryId||'',serviceIds:Array.isArray(req.serviceIds)?req.serviceIds:[],expandedServiceIds:services,primaryServiceId:primary,selectedPackageId:req.selectedPackageId||null,score:scoreNum,comment:cleanComment(comment),status:'active',moderationStatus:'unreviewed',createdAt:previous?.createdAt||now,updatedAt:now,schemaVersion:SCHEMA_VERSION}; tx.set(ratingRef,record,{merge:true}); tx.set(requestRef,{ratings:{...(req.ratings||{}),[embedKey]:{score:scoreNum,comment:cleanComment(comment),ratedUserId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}},updatedAt:now},{merge:true});
  const accRef=db.collection('ratingAccounts').doc(ratedUserId); const deltaCount=old.exists?0:1; const deltaScore=scoreNum-(oldScore||0); tx.set(accRef,{userId:ratedUserId,accountType:ratedRole,overallCount:admin.firestore.FieldValue.increment(deltaCount),totalScore:admin.firestore.FieldValue.increment(deltaScore),overallAverage:0,...distInc('distribution',oldScore,scoreNum,admin),updatedAt:now,schemaVersion:SCHEMA_VERSION},{merge:true}); for(const sid of services){ tx.set(accRef.collection('services').doc(sid),{userId:ratedUserId,serviceId:sid,categoryId:req.categoryId||'',count:admin.firestore.FieldValue.increment(deltaCount),totalScore:admin.firestore.FieldValue.increment(deltaScore),average:0,...distInc('distribution',oldScore,scoreNum,admin),updatedAt:now,schemaVersion:SCHEMA_VERSION},{merge:true}); }});
 await recomputeAverages(db,admin,ratedUserId,services); const accountType=ratedRole==='helper'?ACCOUNT_TYPES.HELPER:ACCOUNT_TYPES.CUSTOMER; const cfg=await getRewardConfig(db, accountType); const effects=cfg.ratingReceivedEffects||{}; const prevEffect=previous?Number(effects[previous.score]||0):0; const nextEffect=Number(effects[scoreNum]||0); const diff=nextEffect-prevEffect; if(diff!==0){ await applyRewardTransaction({db,admin,userId:ratedUserId,accountType,direction:diff>0?REWARD_TRANSACTION_DIRECTIONS.CREDIT:REWARD_TRANSACTION_DIRECTIONS.DEBIT,points:Math.abs(diff),reasonCode:REWARD_REASON_CODES.RATING_RECEIVED_EFFECT,reasonLabel:'Rating received effect',sourceType:'rating',sourceId:ratingId,idempotencyKey:`${accountType}:${ratedUserId}:rating:${ratingId}:received-effect:${previous?.score||0}->${scoreNum}`,requestId,ratingId,relatedUserId:raterUserId,categoryId:req.categoryId||'',serviceIds:services,primaryServiceId:primary,allowNegativeBalance:diff<0}); }
 logger.info('rating_normalized',{ratingId,requestId,raterUserId,ratedUserId,direction,result:'ok'}); return {ratingId,direction,ratedUserId,score:scoreNum}; }
async function recomputeAverages(db,admin,userId,services){ const ref=db.collection('ratingAccounts').doc(userId); const snap=await ref.get(); const d=snap.data()||{}; const avg=Number(d.overallCount||0)>0?Number((Number(d.totalScore||0)/Number(d.overallCount)).toFixed(3)):0; await ref.set({overallAverage:avg,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true}); for(const sid of services){ const sref=ref.collection('services').doc(sid); const ss=await sref.get(); const sd=ss.data()||{}; const a=Number(sd.count||0)>0?Number((Number(sd.totalScore||0)/Number(sd.count)).toFixed(3)):0; await sref.set({average:a,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true}); }}
module.exports={submitServiceRequestRating,serviceIdsFor};
