const { createHash, randomBytes } = require('crypto');
const { logger } = require('firebase-functions');
const { ACCOUNT_TYPES, REFERRAL_STATUSES, REWARD_REASON_CODES, REWARD_TRANSACTION_DIRECTIONS, SCHEMA_VERSION, normalizeReferralCode } = require('../../shared/rewards');
const { applyRewardTransaction } = require('./rewardService');
const { getRewardConfig } = require('./config');
function baseCode(userId, displayName=''){ const seed=String(displayName||userId).toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)||'UNCEDO'; const hash=createHash('sha1').update(`${userId}:${displayName}`).digest('hex').slice(0,4).toUpperCase(); return `${seed}${hash}`; }
async function ensureReferralCode({db,admin,userId,accountType=ACCOUNT_TYPES.CUSTOMER,displayName=''}){ const userRef=db.collection('users').doc(userId); const userSnap=await userRef.get(); const existing=normalizeReferralCode(userSnap.data()?.referralCode||userSnap.data()?.referralSlug||''); if(existing){ const ref=db.collection('referralCodes').doc(existing); const snap=await ref.get(); if(!snap.exists||snap.data()?.ownerUserId===userId){ await ref.set({code:existing,normalizedCode:existing,ownerUserId:userId,ownerAccountType:accountType,status:REFERRAL_STATUSES.ACTIVE,createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp(),schemaVersion:SCHEMA_VERSION},{merge:true}); await userRef.set({referralCode:existing,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true}); return {code:existing}; }}
 for(let i=0;i<8;i++){ const code=normalizeReferralCode(`${baseCode(userId,displayName)}${i?randomBytes(2).toString('hex').toUpperCase():''}`); const ref=db.collection('referralCodes').doc(code); try{ await db.runTransaction(async tx=>{ const s=await tx.get(ref); if(s.exists&&s.data()?.ownerUserId!==userId) throw new Error('collision'); tx.set(ref,{code,normalizedCode:code,ownerUserId:userId,ownerAccountType:accountType,status:REFERRAL_STATUSES.ACTIVE,createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp(),schemaVersion:SCHEMA_VERSION},{merge:true}); tx.set(userRef,{referralCode:code,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true}); }); return {code}; }catch(e){ if(e.message!=='collision') throw e; }} throw new Error('Unable to allocate unique referral code'); }
async function attachReferral({db,admin,referralCode,referredUserId,referredAccountType=ACCOUNT_TYPES.CUSTOMER}){ const code=normalizeReferralCode(referralCode); if(!code) throw new Error('Referral code is required'); const codeSnap=await db.collection('referralCodes').doc(code).get(); if(!codeSnap.exists||codeSnap.data()?.status!==REFERRAL_STATUSES.ACTIVE) throw new Error('Referral code is not active'); const codeData=codeSnap.data(); if(codeData.ownerUserId===referredUserId) throw new Error('Self-referral is not allowed'); const ref=db.collection('referrals').doc(referredUserId); await db.runTransaction(async tx=>{ const rel=await tx.get(ref); if(rel.exists) throw new Error('Referral relationship already exists'); const user=await tx.get(db.collection('users').doc(referredUserId)); if(user.exists&&user.data()?.createdAt){ /* foundation only: caller should use during onboarding */ } tx.set(ref,{referralId:referredUserId,referralCode:code,referrerUserId:codeData.ownerUserId,referrerAccountType:codeData.ownerAccountType,referredUserId,referredAccountType,status:REFERRAL_STATUSES.ATTRIBUTED,attributedAt:admin.firestore.FieldValue.serverTimestamp(),fraudReviewStatus:'clear',createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp(),schemaVersion:SCHEMA_VERSION}); }); logger.info('referral_created',{referralCode:code,referredUserId,referrerUserId:codeData.ownerUserId}); return {attached:true,referrerAccountType:codeData.ownerAccountType}; }
async function awardReferralStage({db,admin,referredUserId,stage,requestId=null}){ const ref=db.collection('referrals').doc(referredUserId); const snap=await ref.get(); if(!snap.exists) return {skipped:true,reason:'no_referral'}; const rel=snap.data(); if(rel.fraudReviewStatus==='invalid'||rel.status==='invalid') return {skipped:true,reason:'invalid'}; const cfg=await getRewardConfig(db, rel.referrerAccountType==='helper'?'helper':'customer'); const points= stage===1 ? (cfg.rewards?.referralStageOne||cfg.rewards?.referralReward||0) : (cfg.rewards?.referralStageTwo||cfg.rewards?.referralReward||0); if(!points) return {skipped:true,reason:'no_points_configured'}; const field=stage===1?'stageOneAwardedAt':'stageTwoAwardedAt'; if(rel[field]) return {skipped:true,reason:'already_awarded'}; const reasonCode=stage===1?REWARD_REASON_CODES.REFERRAL_STAGE_ONE:REWARD_REASON_CODES.REFERRAL_STAGE_TWO; const result=await applyRewardTransaction({db,admin,userId:rel.referrerUserId,accountType:rel.referrerAccountType,direction:REWARD_TRANSACTION_DIRECTIONS.CREDIT,points,reasonCode,reasonLabel:`Referral stage ${stage}`,sourceType:'referral',sourceId:referredUserId,idempotencyKey:`referral:${referredUserId}:stage-${stage}`,referralId:referredUserId,relatedUserId:referredUserId,requestId}); await ref.set({[field]:admin.firestore.FieldValue.serverTimestamp(),status:stage===2?REFERRAL_STATUSES.REWARDED:REFERRAL_STATUSES.QUALIFIED,updatedAt:admin.firestore.FieldValue.serverTimestamp()}, {merge:true}); logger.info('referral_milestone_achieved',{referredUserId,stage,result}); return result; }
module.exports={ensureReferralCode,attachReferral,awardReferralStage};
