const { createHash } = require('crypto');
const { logger } = require('firebase-functions');
const { ACCOUNT_TYPES, MEMBERSHIP_LEVELS, REWARD_TRANSACTION_DIRECTIONS, REWARD_TRANSACTION_STATUSES, REWARD_REASON_CODES, SCHEMA_VERSION, assertIntegerPoints } = require('../../shared/rewards');
const { getRewardConfig } = require('./config');
function txIdFromKey(key){return createHash('sha256').update(String(key)).digest('hex').slice(0,40)}
function monthsFrom(date, months){ const d=new Date(date); d.setMonth(d.getMonth()+Number(months||0)); return d; }
function accountBase(userId, accountType, admin){ return { userId, accountType, availablePoints:0,pendingPoints:0,lifetimeEarnedPoints:0,lifetimeRedeemedPoints:0,lifetimeExpiredPoints:0,lifetimeDeductedPoints:0,lifetimeReversedPoints:0, eligibleCompletedPaidBookings:0, eligibleCompletedPaidJobs:0, membership:{ currentLevel:'neighbour', highestLevel:'neighbour', currentLevelIndex:0, qualificationSnapshot:{}, progressToNextLevel:{}, achievedAt: admin.firestore.FieldValue.serverTimestamp()}, referralSummary:{totalAttributed:0,totalQualified:0,totalRewarded:0}, pointsExpiringSoon:0,nextExpiryAt:null, createdAt:admin.firestore.FieldValue.serverTimestamp(), updatedAt:admin.firestore.FieldValue.serverTimestamp(), schemaVersion:SCHEMA_VERSION}; }
async function ensureRewardAccount(db, admin, tx, userId, accountType){ const ref=db.collection('rewardAccounts').doc(userId); const snap= await tx.get(ref); if(!snap.exists) tx.set(ref, accountBase(userId, accountType, admin), {merge:true}); return ref; }
async function applyRewardTransaction({db, admin, userId, accountType=ACCOUNT_TYPES.CUSTOMER, direction, points, reasonCode, reasonLabel='', sourceType='', sourceId='', idempotencyKey, requestId=null, ratingId=null, referralId=null, relatedUserId=null, categoryId='', serviceIds=[], primaryServiceId='', metadata={}, allowNegativeBalance=false}){
 assertIntegerPoints(points); if(points<=0) throw new Error('points must be positive'); if(!userId||!idempotencyKey||!direction||!reasonCode) throw new Error('missing reward transaction fields');
 const transactionId=txIdFromKey(idempotencyKey); const txRef=db.collection('rewardAccounts').doc(userId).collection('transactions').doc(transactionId);
 return db.runTransaction(async tx=>{ const existing=await tx.get(txRef); if(existing.exists){ logger.info('reward_duplicate_skipped',{userId,idempotencyKey,reasonCode,result:'duplicate'}); return {applied:false,duplicate:true,transactionId}; }
  const accountRef=await ensureRewardAccount(db,admin,tx,userId,accountType); const accountSnap=await tx.get(accountRef); const account=accountSnap.data()||accountBase(userId,accountType,admin); let delta=0, fields={ updatedAt:admin.firestore.FieldValue.serverTimestamp() };
  if(direction===REWARD_TRANSACTION_DIRECTIONS.CREDIT){ delta=points; fields.availablePoints=admin.firestore.FieldValue.increment(points); fields.lifetimeEarnedPoints=admin.firestore.FieldValue.increment(points); }
  else if(direction===REWARD_TRANSACTION_DIRECTIONS.DEBIT){ delta=-points; if(!allowNegativeBalance && Number(account.availablePoints||0)<points) throw new Error('insufficient reward points'); fields.availablePoints=admin.firestore.FieldValue.increment(-points); fields.lifetimeRedeemedPoints=admin.firestore.FieldValue.increment(points); }
  else if(direction===REWARD_TRANSACTION_DIRECTIONS.EXPIRY){ delta=-points; if(!allowNegativeBalance && Number(account.availablePoints||0)<points) throw new Error('insufficient reward points'); fields.availablePoints=admin.firestore.FieldValue.increment(-points); fields.lifetimeExpiredPoints=admin.firestore.FieldValue.increment(points); }
  else if(direction===REWARD_TRANSACTION_DIRECTIONS.REVERSAL){ delta=-points; fields.availablePoints=admin.firestore.FieldValue.increment(-points); fields.lifetimeReversedPoints=admin.firestore.FieldValue.increment(points); }
  else throw new Error('unsupported reward direction');
  const global=await getRewardConfig(db,'global'); const now=new Date(); const expiresAt= accountType===ACCOUNT_TYPES.CUSTOMER && direction==='credit' ? monthsFrom(now, global.customerPointExpiryMonths) : null;
  tx.set(txRef,{ transactionId,userId,accountType,direction,points,status:REWARD_TRANSACTION_STATUSES.APPLIED,reasonCode,reasonLabel,sourceType,sourceId,idempotencyKey,requestId,ratingId,referralId,relatedUserId,categoryId,serviceIds:Array.isArray(serviceIds)?serviceIds:[],primaryServiceId,availableAt:admin.firestore.FieldValue.serverTimestamp(),expiresAt,createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp(),metadata: sanitizeMetadata(metadata),schemaVersion:SCHEMA_VERSION });
  tx.set(accountRef, fields, {merge:true}); logger.info('reward_applied',{userId,idempotencyKey,reasonCode,direction,points,result:'applied'}); return {applied:true,duplicate:false,transactionId,delta}; }); }
function sanitizeMetadata(metadata){ const out={}; Object.entries(metadata||{}).slice(0,20).forEach(([k,v])=>{ if(/token|secret|authorization|card|payload/i.test(k)) return; if(['string','number','boolean'].includes(typeof v)||v===null) out[k]=v; }); return out; }
async function reverseReward({db, admin, userId, accountType, originalTransactionId, points, reason='reward_reversal', idempotencyKey}){ return applyRewardTransaction({db,admin,userId,accountType,direction:REWARD_TRANSACTION_DIRECTIONS.REVERSAL,points,reasonCode:REWARD_REASON_CODES.REVERSAL,reasonLabel:reason,sourceType:'reward_transaction',sourceId:originalTransactionId,idempotencyKey,metadata:{originalTransactionId},allowNegativeBalance:true}); }
async function processExpiredCustomerPoints({db, admin, limit=100}){ const now=admin.firestore.Timestamp.now(); const snap=await db.collectionGroup('transactions').where('accountType','==','customer').where('direction','==','credit').where('status','==','applied').where('expiresAt','<=',now).limit(limit).get(); let processed=0; for(const doc of snap.docs){ const data=doc.data(); const idempotencyKey=`customer:${data.userId}:points-expired:${data.transactionId}`; const res=await applyRewardTransaction({db,admin,userId:data.userId,accountType:'customer',direction:'expiry',points:data.points,reasonCode:REWARD_REASON_CODES.POINTS_EXPIRED,reasonLabel:'Points expired',sourceType:'reward_transaction',sourceId:data.transactionId,idempotencyKey,allowNegativeBalance:false}).catch(e=>({error:e.message})); if(!res.error) { await doc.ref.set({status:'expired',updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true}); processed++; }} logger.info('expiry_processed',{processed}); return {processed}; }
module.exports={ensureRewardAccount,applyRewardTransaction,reverseReward,processExpiredCustomerPoints,txIdFromKey,accountBase};
