import { collection, doc, getDoc, getDocs, limit, orderBy, query, where } from 'firebase/firestore';
import { getFirebaseClients, getFunctionEndpoint } from '../../firebase/config';
export async function getRewardAccount(userId) { const { db } = getFirebaseClients(); const snap = await getDoc(doc(db, 'rewardAccounts', userId)); return snap.exists() ? { id: snap.id, ...snap.data() } : null; }
export async function getRewardTransactions(userId, pageSize = 25) { const { db } = getFirebaseClients(); const snap = await getDocs(query(collection(db, 'rewardAccounts', userId, 'transactions'), orderBy('createdAt', 'desc'), limit(pageSize))); return snap.docs.map((item) => ({ id: item.id, ...item.data() })); }
export async function getRewardConfig(section = 'global') { const { db } = getFirebaseClients(); const snap = await getDoc(doc(db, 'rewardConfig', section)); return snap.exists() ? { id: snap.id, ...snap.data() } : null; }
export async function getMembershipSummary(userId) { const account = await getRewardAccount(userId); return account?.membership || null; }
export async function getRatingSummary(userId) { const { db } = getFirebaseClients(); const snap = await getDoc(doc(db, 'ratingAccounts', userId)); return snap.exists() ? { id: snap.id, ...snap.data() } : null; }
export async function getReferralCode(userId) { const { db } = getFirebaseClients(); const userSnap = await getDoc(doc(db, 'users', userId)); return userSnap.exists() ? (userSnap.data()?.referralCode || userSnap.data()?.referralSlug || null) : null; }
export async function ensureMyReferralCode(accountType) { const { auth } = getFirebaseClients(); const token = await auth.currentUser?.getIdToken(); if (!token) throw new Error('You must be signed in.'); const res = await fetch(getFunctionEndpoint('ensureReferralCode'), { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ accountType }) }); const payload = await res.json().catch(() => null); if (!res.ok || payload?.success === false) throw new Error(payload?.message || 'Unable to load referral code.'); return payload.code; }
export async function captureReferralCode(referralCode, accountType) { const { auth } = getFirebaseClients(); const token = await auth.currentUser?.getIdToken(); if (!token) throw new Error('You must be signed in.'); const res = await fetch(getFunctionEndpoint('captureReferral'), { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ referralCode, accountType }) }); const payload = await res.json().catch(() => null); if (!res.ok || payload?.success === false) throw new Error(payload?.message || 'Unable to apply referral code.'); return payload; }
export async function getHelperMasterySummary(helperId) { const { db } = getFirebaseClients(); const snap = await getDocs(collection(db, 'helperMastery', helperId, 'services')); return snap.docs.map((item) => ({ id: item.id, ...item.data() })); }
export async function getMyReferralRelationships(userId) { const { db } = getFirebaseClients(); const asReferred = await getDoc(doc(db, 'referrals', userId)); const referredByMe = await getDocs(query(collection(db, 'referrals'), where('referrerUserId', '==', userId), limit(50))); return { attributed: asReferred.exists() ? { id: asReferred.id, ...asReferred.data() } : null, referred: referredByMe.docs.map((item) => ({ id: item.id, ...item.data() })) }; }
